# Example config file 

# The ports to listen on 
ports:
   http: 8010
   json: 8009
   bin: 8011

# Http specific settings
http: 
   # Static files for serving js/css/ect for http only 
   static_files: 
      route: /static
      directory: static
   websockets: 
      route: /ws
   html: 
      view_directory: views

